name: Main
# on: push
on: workflow_dispatch
jobs:
    setupEnviroment:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
    test:
        runs-on: ubuntu-latest
        needs: [setupEnviroment]
        steps:
            - name: Test application
              run: npm run test
    lint:
        runs-on: ubuntu-latest
        needs: [setupEnviroment]
        steps:
            - name: Lint application
              run: npm run lint
    build:
        runs-on: ubuntu-latest
        needs: [setupEnviroment]
        steps:
            - name: Build application
              run: npm run build
